namespace PROJECT {
  export class CameraController extends TOOLKIT.ScriptComponent {
    public player: BABYLON.TransformNode;

    public mDampTime: number = 0.2;
    public maxSpeed: number = 2;
    public mMinSize: number = 6.5;
    public mMaxSize: number = 20;

    private mCamera: BABYLON.Camera;
    private mZoomSpeed: number = 0;
    private mMoveVelocity: BABYLON.Vector3 = BABYLON.Vector3.Zero();
    private mDesiredPosition: BABYLON.Vector3 = BABYLON.Vector3.Zero();

    constructor(transform: BABYLON.TransformNode, scene: BABYLON.Scene, properties: any = {}, alias: string = "PROJECT.CameraController") {
      super(transform, scene, properties, alias);
    }

    protected awake(): void {
      // Get the first child camera in the transform's descendants
      let cameras: BABYLON.Camera[] = [];
      this.transform.getChildMeshes(false).forEach(child => {
        if ((child as any).camera) {
          cameras.push((child as any).camera as BABYLON.Camera);
        }
      });
      if (cameras.length > 0) {
        this.mCamera = cameras[0];
      } else {
        // fallback: try to get the first camera in the scene
        if (this.scene.cameras.length > 0) {
          this.mCamera = this.scene.cameras[0];
        }
      }
      this.maxSpeed *= 100;
    }

    protected update(): void {
      this.move();
      this.zoom();
    }

    private move(): void {
      if (!this.player) return;
      let averagePos: BABYLON.Vector3 = this.player.position.clone();
      averagePos.y = this.transform.position.y;

      // SmoothDamp approximation using Lerp for Babylon.js
      let t: number = this.mDampTime / (this.mDampTime + this.getDeltaTime());
      this.transform.position = BABYLON.Vector3.Lerp(this.transform.position, averagePos, 1 - t);
    }

    private zoom(): void {
      if (!this.mCamera) return;
      let requiredSize: number = (this.mCamera as any).orthoTop !== undefined
        ? Math.abs((this.mCamera as any).orthoTop)
        : 10;

      // Mouse wheel input (Babylon.js)
      let inputDelta: number = 0;
      if ((window as any).IC && typeof (window as any).IC.GetPointerWheelDelta === "function") {
        inputDelta = (window as any).IC.GetPointerWheelDelta();
      } else if ((window as any).TOOLKIT && (window as any).TOOLKIT.InputController && typeof (window as any).TOOLKIT.InputController.GetPointerWheelDelta === "function") {
        inputDelta = (window as any).TOOLKIT.InputController.GetPointerWheelDelta();
      }

      if (inputDelta !== 0) {
        requiredSize += (this.getDeltaTime() * 1000 * -Math.sign(inputDelta));
      }

      requiredSize = Math.max(this.mMinSize, Math.min(requiredSize, this.mMaxSize));

      // SmoothDamp approximation using Lerp for Babylon.js
      let t: number = this.mDampTime / (this.mDampTime + this.getDeltaTime());
      let currentSize: number = (this.mCamera as any).orthoTop !== undefined
        ? Math.abs((this.mCamera as any).orthoTop)
        : 10;
      let newSize: number = BABYLON.Scalar.Lerp(currentSize, requiredSize, 1 - t);

      // Set orthographic size (Babylon.js orthographic camera)
      if ((this.mCamera as any).mode === BABYLON.Camera.ORTHOGRAPHIC_CAMERA) {
        (this.mCamera as any).orthoTop = newSize;
        (this.mCamera as any).orthoBottom = -newSize;
        (this.mCamera as any).orthoLeft = -newSize * this.mCamera.getEngine().getAspectRatio(this.mCamera);
        (this.mCamera as any).orthoRight = newSize * this.mCamera.getEngine().getAspectRatio(this.mCamera);
      }
    }
  }
}
// Pseudocode generated by codewrx.ai