namespace PROJECT {
  export class Heart extends TOOLKIT.ScriptComponent {
    public life: number = 10; // The amount of health is given to the player.
    public rotateSpeed: number = 50; // The speed that the heart will rotate at.

    constructor(transform: BABYLON.TransformNode, scene: BABYLON.Scene, properties: any = {}, alias: string = "PROJECT.Heart") {
      super(transform, scene, properties, alias);
    }

    protected start(): void {
      console.log("Heart: start() called, setting up trigger events");
      this.transform.rotation = new BABYLON.Vector3(-Math.PI / 2, 0, 0);
      
      // Enable collision events for triggers
      this.enableCollisionEvents();
      
      // Debug: Check if physicsBody exists
      if (this.transform.physicsBody) {
        console.log("Heart: physicsBody exists", this.transform.physicsBody);
      } else {
        console.warn("Heart: No physicsBody found!");
      }
      
      // Subscribe to trigger enter observable
      this.onTriggerEnterObservable.add((other: BABYLON.TransformNode) => {
        console.log("Heart: Trigger entered by:", other.name, "Tag:", TOOLKIT.SceneManager.GetTransformTag(other));
        
        if (TOOLKIT.SceneManager.GetTransformTag(other) === "Player") {
          let player = TOOLKIT.SceneManager.FindGameObjectWithTag(this.scene, "Player") as BABYLON.TransformNode;
          let playerHealth = player ? TOOLKIT.SceneManager.GetComponent(player, "PROJECT.PlayerHealth") as PROJECT.PlayerHealth : null;
          if (playerHealth && playerHealth.currentHealth > 0) {
            playerHealth.getLife(this.life);
          }
          
          // Dispose lights before destroying
          this.disposeLights();
          TOOLKIT.SceneManager.SafeDestroy(this.transform);
        }
      });
    }

    protected update(): void {
      // Spin the object around the world origin at 20 degrees/second.
      let deltaTime: number = this.getDeltaTime();
      let up: BABYLON.Vector3 = BABYLON.Vector3.Up();
      let angle: number = this.rotateSpeed * deltaTime * (Math.PI / 180);
      this.transform.rotate(up, angle, BABYLON.Space.WORLD);
    }

    private disposeLights(): void {
      if (!this.transform || this.transform.isDisposed()) return;
      
      try {
        const allLights = this.scene.lights.slice();
        
        for (let light of allLights) {
          try {
            let lightNode = light as any;
            if (lightNode.parent === this.transform) {
              light.setEnabled(false);
              setTimeout(() => {
                if (!light.isDisposed()) {
                  light.dispose();
                }
              }, 0);
            }
          } catch (e) {}
        }
        
        const children = this.transform.getChildren();
        for (let child of children) {
          for (let light of this.scene.lights.slice()) {
            try {
              if (light === child || (light as any).parent === child) {
                light.setEnabled(false);
                setTimeout(() => {
                  if (!light.isDisposed()) {
                    light.dispose();
                  }
                }, 0);
              }
            } catch (e) {}
          }
        }
      } catch (e) {}
    }
  }
}
// Pseudocode generated by codewrx.ai