namespace PROJECT {
  export class Heart extends TOOLKIT.ScriptComponent {
    public life: number = 10; // The amount of health is given to the player.
    public rotateSpeed: number = 50; // The speed that the heart will rotate at.

    constructor(transform: BABYLON.TransformNode, scene: BABYLON.Scene, properties: any = {}, alias: string = "PROJECT.Heart") {
      super(transform, scene, properties, alias);
    }

    protected start(): void {
      console.log("Heart: start() called, setting up trigger events");
      this.transform.rotation = new BABYLON.Vector3(-Math.PI / 2, 0, 0);
      
      // Enable collision events for triggers
      this.enableCollisionEvents();
      
      // Debug: Check if physicsBody exists
      if (this.transform.physicsBody) {
        console.log("Heart: physicsBody exists", this.transform.physicsBody);
      } else {
        console.warn("Heart: No physicsBody found!");
      }
      
      // Subscribe to trigger enter observable
      this.onTriggerEnterObservable.add((other: BABYLON.TransformNode) => {
        console.log("Heart: Trigger entered by:", other.name, "Tag:", TOOLKIT.SceneManager.GetTransformTag(other));
        
        if (TOOLKIT.SceneManager.GetTransformTag(other) === "Player") {
          console.log("Heart: Player detected, giving life");
          let player = TOOLKIT.SceneManager.FindGameObjectWithTag(this.scene, "Player") as BABYLON.TransformNode;
          let playerHealth = player ? TOOLKIT.SceneManager.GetComponent(player, "PROJECT.PlayerHealth") as PROJECT.PlayerHealth : null;
          if (playerHealth && playerHealth.currentHealth > 0) {
            playerHealth.getLife(this.life);
            console.log("Heart: Life given to player, destroying heart");
          }
          TOOLKIT.SceneManager.SafeDestroy(this.transform);
        }
      });
      
      console.log("Heart: Trigger observable setup complete");
    }

    protected update(): void {
      // Spin the object around the world origin at 20 degrees/second.
      let deltaTime: number = this.getDeltaTime();
      let up: BABYLON.Vector3 = BABYLON.Vector3.Up();
      let angle: number = this.rotateSpeed * deltaTime * (Math.PI / 180);
      this.transform.rotate(up, angle, BABYLON.Space.WORLD);
    }

    // ...existing code...
  }
}
// Pseudocode generated by codewrx.ai