namespace PROJECT {
  export class Puddle extends TOOLKIT.ScriptComponent {
    public timeToInvertControls: number = 8.0;

    private player: BABYLON.TransformNode;

    constructor(transform: BABYLON.TransformNode, scene: BABYLON.Scene, properties: any = {}, alias: string = "PROJECT.Puddle") {
      super(transform, scene, properties, alias);
    }

    protected start(): void {
      console.log("Puddle: start() called, setting up trigger events");
      this.player = TOOLKIT.SceneManager.FindGameObjectWithTag(this.scene, "Player") as BABYLON.TransformNode;
      console.log("Puddle: Player Transform:", this.player);
      this.transform.position = this.findTheClosestSpawnPoint();
      
      // Enable collision events for triggers
      this.enableCollisionEvents();
      
      // Debug: Check if physicsBody exists
      if (this.transform.physicsBody) {
        console.log("Puddle: physicsBody exists", this.transform.physicsBody);
      } else {
        console.warn("Puddle: No physicsBody found!");
      }
      
      // Subscribe to trigger enter observable
      this.onTriggerEnterObservable.add((other: BABYLON.TransformNode) => {
        console.log("Puddle: Trigger entered by:", other.name, "Tag:", TOOLKIT.SceneManager.GetTransformTag(other));
        
        if (TOOLKIT.SceneManager.GetTransformTag(other) === "Player") {
          console.log("Puddle: Player detected, inverting controls");
          const playerHealth = TOOLKIT.SceneManager.GetComponent(this.player, "PROJECT.PlayerHealth") as PROJECT.PlayerHealth;
          if (playerHealth && playerHealth.currentHealth > 0) {
            const playerMovement = TOOLKIT.SceneManager.GetComponent(this.player, "PROJECT.PlayerMovement") as any;
            if (playerMovement && typeof playerMovement.invertControls === "function") {
              playerMovement.invertControls(this.timeToInvertControls);
              console.log("Puddle: Controls inverted, destroying puddle after delay");
            }
          }
          // Remove puddle after a short delay (1.5s)
          setTimeout(() => {
            this.disposeLights();
            TOOLKIT.SceneManager.SafeDestroy(this.transform);
          }, 1500);
        }
      });
    }

    private disposeLights(): void {
      if (!this.transform || this.transform.isDisposed()) return;
      
      try {
        const allLights = this.scene.lights.slice();
        
        for (let light of allLights) {
          try {
            let lightNode = light as any;
            if (lightNode.parent === this.transform) {
              light.setEnabled(false);
              setTimeout(() => {
                if (!light.isDisposed()) {
                  light.dispose();
                }
              }, 0);
            }
          } catch (e) {}
        }
        
        const children = this.transform.getChildren();
        for (let child of children) {
          for (let light of this.scene.lights.slice()) {
            try {
              if (light === child || (light as any).parent === child) {
                light.setEnabled(false);
                setTimeout(() => {
                  if (!light.isDisposed()) {
                    light.dispose();
                  }
                }, 0);
              }
            } catch (e) {}
          }
        }
      } catch (e) {}
    }

    private findTheClosestSpawnPoint(): BABYLON.Vector3 {
      const spawnPointsParent = TOOLKIT.SceneManager.FindGameObjectWithTag(this.scene, "PuddleSpawn") as BABYLON.TransformNode;

      let closestSpawnPoint: BABYLON.Vector3 = new BABYLON.Vector3(Number.POSITIVE_INFINITY, Number.POSITIVE_INFINITY, Number.POSITIVE_INFINITY);
      let minDistance: number = Number.POSITIVE_INFINITY;

      for (const spawnPoint of spawnPointsParent.getChildTransformNodes()) {
        const newDistance: number = BABYLON.Vector3.Distance(spawnPoint.position, this.player.position);
        if (newDistance < minDistance || closestSpawnPoint.equalsWithEpsilon(new BABYLON.Vector3(Number.POSITIVE_INFINITY, Number.POSITIVE_INFINITY, Number.POSITIVE_INFINITY))) {
          minDistance = newDistance;
          closestSpawnPoint = spawnPoint.position.clone();
        }
      }

      return closestSpawnPoint;
    }
  }
}
// Pseudocode generated by codewrx.ai