namespace PROJECT {
  export class Shield extends TOOLKIT.ScriptComponent {
    public timeToShield: number = 10.0;
    public timeToNextDest: number = 3.5;
    private nav: TOOLKIT.NavigationAgent;
    private spawnPoints: BABYLON.TransformNode;

    constructor(transform: BABYLON.TransformNode, scene: BABYLON.Scene, properties: any = {}, alias: string = "PROJECT.Shield") {
      super(transform, scene, properties, alias);
    }

    protected start(): void {
      console.log("Shield: start() called, setting up trigger events");
      this.nav = TOOLKIT.SceneManager.GetComponent(this.transform, "TOOLKIT.NavigationAgent") as TOOLKIT.NavigationAgent;
      const spawnPointsScript = TOOLKIT.SceneManager.SearchForScriptComponentByName(this.scene, "PROJECT.ShieldSpawnPoints") as TOOLKIT.ScriptComponent;
      this.spawnPoints = spawnPointsScript ? spawnPointsScript.transform : null;
      this.moveToNextDest();
      
      // Enable collision events for triggers
      this.enableCollisionEvents();
      
      // Debug: Check if physicsBody exists
      if (this.transform.physicsBody) {
        console.log("Shield: physicsBody exists", this.transform.physicsBody);
      } else {
        console.warn("Shield: No physicsBody found!");
      }
      
      // Subscribe to trigger enter observable
      this.onTriggerEnterObservable.add((other: BABYLON.TransformNode) => {
        console.log("Shield: Trigger entered by:", other.name, "Tag:", TOOLKIT.SceneManager.GetTransformTag(other));
        
        if (TOOLKIT.SceneManager.GetTransformTag(other) === "Player") {
          console.log("Shield: Player detected, adding shield");
          let playerHealth = TOOLKIT.SceneManager.GetComponent(other, "PROJECT.PlayerHealth") as PROJECT.PlayerHealth;
          if (playerHealth && playerHealth.currentHealth > 0) {
            playerHealth.addShield(this.timeToShield);
            console.log("Shield: Shield added to player, destroying shield");
          }
          TOOLKIT.SceneManager.SafeDestroy(this.transform);
        }
      });
      
      console.log("Shield: Trigger observable setup complete");
    }

    private async moveToNextDest(): Promise<void> {
      if (!this.spawnPoints) return;
      let childCount: number = this.spawnPoints.getChildTransformNodes().length;
      let spawnPointIndex: number = Math.floor(Math.random() * childCount);
      let spawnChild: BABYLON.TransformNode = this.spawnPoints.getChildTransformNodes()[spawnPointIndex];
      this.nav.setDestination(spawnChild.position);

      await TOOLKIT.SceneManager.WaitForSeconds(this.timeToNextDest);

      this.moveToNextDest();
    }
  }
}
// Pseudocode generated by codewrx.ai