namespace PROJECT {
  export class Shield extends TOOLKIT.ScriptComponent {
    public timeToShield: number = 10.0;
    public timeToNextDest: number = 3.5;
    private nav: TOOLKIT.NavigationAgent;
    private spawnPoints: BABYLON.TransformNode;

    constructor(transform: BABYLON.TransformNode, scene: BABYLON.Scene, properties: any = {}, alias: string = "PROJECT.Shield") {
      super(transform, scene, properties, alias);
    }

    protected start(): void {
      this.nav = TOOLKIT.SceneManager.GetComponent(this.transform, "TOOLKIT.NavigationAgent") as TOOLKIT.NavigationAgent;
      const spawnPointsScript = TOOLKIT.SceneManager.SearchForScriptComponentByName(this.scene, "PROJECT.ShieldSpawnPoints") as TOOLKIT.ScriptComponent;
      this.spawnPoints = spawnPointsScript ? spawnPointsScript.transform : null;
      this.moveToNextDest();
      
      // Enable collision events for triggers
      this.enableCollisionEvents();
      
      // Subscribe to trigger enter observable
      this.onTriggerEnterObservable.add((other: BABYLON.TransformNode) => {
        if (TOOLKIT.SceneManager.GetTransformTag(other) === "Player") {
          let playerHealth = TOOLKIT.SceneManager.GetComponent(other, "PROJECT.PlayerHealth") as PROJECT.PlayerHealth;
          if (playerHealth && playerHealth.currentHealth > 0) {
            playerHealth.addShield(this.timeToShield);
          }
          
          // Dispose lights before destroying
          this.disposeLights();
          TOOLKIT.SceneManager.SafeDestroy(this.transform);
        }
      });
    }

    private async moveToNextDest(): Promise<void> {
      if (!this.spawnPoints) return;
      let childCount: number = this.spawnPoints.getChildTransformNodes().length;
      let spawnPointIndex: number = Math.floor(Math.random() * childCount);
      let spawnChild: BABYLON.TransformNode = this.spawnPoints.getChildTransformNodes()[spawnPointIndex];
      this.nav.setDestination(spawnChild.position);

      await TOOLKIT.SceneManager.WaitForSeconds(this.timeToNextDest);

      this.moveToNextDest();
    }

    private disposeLights(): void {
      if (!this.transform || this.transform.isDisposed()) return;
      
      try {
        const allLights = this.scene.lights.slice();
        
        for (let light of allLights) {
          try {
            let lightNode = light as any;
            if (lightNode.parent === this.transform) {
              light.setEnabled(false);
              setTimeout(() => {
                if (!light.isDisposed()) {
                  light.dispose();
                }
              }, 0);
            }
          } catch (e) {}
        }
        
        const children = this.transform.getChildren();
        for (let child of children) {
          for (let light of this.scene.lights.slice()) {
            try {
              if (light === child || (light as any).parent === child) {
                light.setEnabled(false);
                setTimeout(() => {
                  if (!light.isDisposed()) {
                    light.dispose();
                  }
                }, 0);
              }
            } catch (e) {}
          }
        }
      } catch (e) {}
    }
  }
}
// Pseudocode generated by codewrx.ai