namespace PROJECT {
  export class Stone extends TOOLKIT.ScriptComponent {
    public damage: number = 20; // The amount of health taken away when hit.
    public height: number = 6; // The height factor of the stone above the player.
    public timeToFollow: number = 1.5; // The time that the stone follow the player.

    private player: BABYLON.TransformNode;
    private timer: number = 0;

    constructor(transform: BABYLON.TransformNode, scene: BABYLON.Scene, properties: any = {}, alias: string = "PROJECT.Stone") {
      super(transform, scene, properties, alias);
    }

    protected start(): void {
      console.log("Stone: start() called, setting up collision events");
      this.player = TOOLKIT.SceneManager.FindGameObjectWithTag(this.scene, "Player") as BABYLON.TransformNode;
      
      // Enable collision events
      this.enableCollisionEvents();
      
      // Debug: Check if physicsBody exists
      if (this.transform.physicsBody) {
        console.log("Stone: physicsBody exists", this.transform.physicsBody);
      } else {
        console.warn("Stone: No physicsBody found!");
      }
      
      // Subscribe to collision enter observable
      this.onCollisionEnterObservable.add((other: BABYLON.TransformNode) => {
        console.log("Stone: Collision with:", other.name, "Tag:", TOOLKIT.SceneManager.GetTransformTag(other));
        
        if (TOOLKIT.SceneManager.GetTransformTag(other) === "Player") {
          console.log("Stone: Player hit, applying damage");
          let playerHealth = TOOLKIT.SceneManager.GetComponent(this.player, "PROJECT.PlayerHealth") as PROJECT.PlayerHealth;
          if (playerHealth && playerHealth.currentHealth > 0) {
            playerHealth.takeDamage(this.damage);
            console.log("Stone: Damage applied, destroying stone after delay");
          }
        }
        
        // Destroy this object after 0.5 seconds
        setTimeout(() => {
          TOOLKIT.SceneManager.SafeDestroy(this.transform);
        }, 500);
      });
      
      console.log("Stone: Collision observable setup complete");
      this.followPlayerCoroutine();
    }

    private async followPlayerCoroutine(): Promise<void> {
      while (this.timer < this.timeToFollow) {
        if (this.player) {
          this.transform.position = this.player.position.add(BABYLON.Vector3.Up().scale(this.height));
        }
        await TOOLKIT.SceneManager.WaitForSeconds(0); // yield return null
      }
    }

    protected update(): void {
      this.timer += this.getDeltaTime();
    }
  }
}
// Pseudocode generated by codewrx.ai