namespace PROJECT {
  export class TNT extends TOOLKIT.ScriptComponent {
    public damageOfExplosion: number = 50;
    public timeOfReductionSpeed: number = 5.0;
    public textures: BABYLON.Texture[] = [];
    public explosionParticle: BABYLON.TransformNode;
    public minWaitTime: number = 5.0;
    public maxWaitTime: number = 10.0;

    private player: BABYLON.TransformNode;
    private isPlayerInsideExplosionArea: boolean = false;

    constructor(transform: BABYLON.TransformNode, scene: BABYLON.Scene, properties: any = {}, alias: string = "PROJECT.TNT") {
      super(transform, scene, properties, alias);
    }

    protected start(): void {
      console.log("TNT: start() called, setting up trigger events");
      this.player = TOOLKIT.SceneManager.FindGameObjectWithTag(this.scene, "Player") as BABYLON.TransformNode;
      
      // Enable collision events for triggers
      this.enableCollisionEvents();
      
      // Debug: Check if physicsBody exists
      if (this.transform.physicsBody) {
        console.log("TNT: physicsBody exists", this.transform.physicsBody);
      } else {
        console.warn("TNT: No physicsBody found!");
      }
      
      // Subscribe to trigger enter observable
      this.onTriggerEnterObservable.add((other: BABYLON.TransformNode) => {
        console.log("TNT: Trigger entered by:", other.name, "Tag:", TOOLKIT.SceneManager.GetTransformTag(other));
        
        if (TOOLKIT.SceneManager.GetTransformTag(other) === "Player") {
          console.log("TNT: Player entered explosion area");
          this.isPlayerInsideExplosionArea = true;
        }
      });
      
      // Subscribe to trigger exit observable
      this.onTriggerExitObservable.add((other: BABYLON.TransformNode) => {
        console.log("TNT: Trigger exited by:", other.name, "Tag:", TOOLKIT.SceneManager.GetTransformTag(other));
        
        if (TOOLKIT.SceneManager.GetTransformTag(other) === "Player") {
          console.log("TNT: Player exited explosion area");
          this.isPlayerInsideExplosionArea = false;
        }
      });
      
      console.log("TNT: Trigger observables setup complete");
      this.explosion();
    }

    private async explosion(): Promise<void> {
      // randomly wait
      let waitTime: number = BABYLON.Scalar.RandomRange(this.minWaitTime, this.maxWaitTime);
      await TOOLKIT.SceneManager.WaitForSeconds(waitTime);

      // Each 1 seconds, set the "TNT_3", then "TNT_2" then "TNT_1" textures to the cube.
      for (let i: number = 0; i < this.textures.length; i++) {
        await TOOLKIT.SceneManager.WaitForSeconds(1.0);
        // Set the main material's texture if possible
        let mesh = this.transform as BABYLON.Mesh;
        if (mesh && mesh.material && (mesh.material as BABYLON.StandardMaterial).diffuseTexture !== undefined) {
          (mesh.material as BABYLON.StandardMaterial).diffuseTexture = this.textures[i];
        }
      }

      // Spawn 5 times the Explosion prefab around the cube position each 0.1 second.
      for (let i: number = 0; i < 5; i++) {
        await TOOLKIT.SceneManager.WaitForSeconds(0.1);
        let randomDirection: BABYLON.Vector3 = BABYLON.Vector3.Random();
        let spawnPosition: BABYLON.Vector3 = this.transform.position.add(randomDirection.add(BABYLON.Vector3.Up()).scale(4));
        // explosionParticle should be an AssetContainer, not a TransformNode
        // If you have an AssetContainer, use it here. Otherwise, skip instantiation.
        // let explosionInstance = TOOLKIT.SceneManager.InstantiatePrefabFromContainer(this.explosionParticleContainer, "ExplosionParticle", "ExplosionParticleInstance" + i);
        // For now, just skip instantiation if not available
        // explosionInstance.position = spawnPosition;
        // setTimeout(() => { explosionInstance.dispose(); }, 2000);
      }

      TOOLKIT.SceneManager.SafeDestroy(this.transform);

      // If the player is inside the trigger, damage the player
      if (this.isPlayerInsideExplosionArea) {
        console.log("TNT: Player was in explosion area, applying damage and speed reduction");
        let playerHealth = TOOLKIT.SceneManager.GetComponent(this.player, "PROJECT.PlayerHealth") as PROJECT.PlayerHealth;
        if (playerHealth) {
          playerHealth.takeDamage(this.damageOfExplosion);
          let playerMovement = TOOLKIT.SceneManager.GetComponent(this.player, "PROJECT.PlayerMovement") as any;
          if (playerMovement && typeof playerMovement.reduceSpeed === "function") {
            playerMovement.reduceSpeed(this.timeOfReductionSpeed);
          }
        }
      }
    }
  }
}
// Pseudocode generated by codewrx.ai