namespace PROJECT {
  export class EnemyBullet extends TOOLKIT.ScriptComponent {
    private enemyShooting: PROJECT.EnemyShooting;
    private explosionParticles: PROJECT.BulletExplosionParticles;
    private isDestroyed: boolean = false;

    constructor(transform: BABYLON.TransformNode, scene: BABYLON.Scene, properties: any = {}, alias: string = "PROJECT.EnemyBullet") {
      super(transform, scene, properties, alias);
    }

    protected awake(): void {
      this.enableCollisionEvents(); // Enable collision events
      let enemy = TOOLKIT.SceneManager.FindGameObjectWithTag(this.scene, "Enemy") as BABYLON.TransformNode;
      this.enemyShooting = TOOLKIT.SceneManager.GetComponent(enemy, "PROJECT.EnemyShooting") as PROJECT.EnemyShooting;
      
      // Get explosion particles component
      this.explosionParticles = TOOLKIT.SceneManager.GetComponent(this.transform, "PROJECT.BulletExplosionParticles") as PROJECT.BulletExplosionParticles;
      
      // Debug collider setup
      if (!this.transform.physicsBody) {
        console.warn("EnemyBullet: No physicsBody on bullet!");
      } else {
        console.log("EnemyBullet: physicsBody exists", this.transform.physicsBody);
      }
      // Subscribing to the collision event
      this.onCollisionEnterObservable.add((otherTransform) => {
        this.handleCollision(otherTransform);
      });
    }

    private handleCollision(other: BABYLON.TransformNode): void {
      console.log("EnemyBullet collided with:", other.name);
      if (this.isDestroyed) return;
      // Ignore collision with Enemy
      if (TOOLKIT.SceneManager.GetTransformTag(other) === "Enemy") {
        return;
      }
      this.isDestroyed = true;
      // Check for Player tag
      if (TOOLKIT.SceneManager.GetTransformTag(other) === "Player") {
        const playerHealth = TOOLKIT.SceneManager.GetComponent(other, "PROJECT.PlayerHealth") as PROJECT.PlayerHealth;
        if (playerHealth && this.enemyShooting) {
          playerHealth.takeDamage(this.enemyShooting.damagePerShot);
        }
      }
      
      // Play explosion particles at collision point
      if (this.explosionParticles) {
        this.explosionParticles.playExplosion(this.transform.position);
      }
      
      // Destroy the bullet after short delay to let particles play
      setTimeout(() => {
        if (this.transform && !this.transform.isDisposed()) {
          TOOLKIT.SceneManager.SafeDestroy(this.transform);
        }
      }, 800);
    }
  }
}
// Pseudocode generated by codewrx.ai