namespace PROJECT {
  export class EnemyShooting extends TOOLKIT.ScriptComponent {
    public timeBetweenShootings: number = 2;
    public damagePerShot: number = 10;
    public distanceToAttack: number = 15;
    public bullet: BABYLON.TransformNode;
    public BulletForce: number = 20;
    public bulletSpawnPoint: BABYLON.TransformNode;

    private player: BABYLON.TransformNode;
    private playerHealth: PROJECT.PlayerHealth;
    private enemyHealth: PROJECT.EnemyHealth;
    private enemyMovement: PROJECT.EnemyMovement;
    private timer: number = 0;

    constructor(transform: BABYLON.TransformNode, scene: BABYLON.Scene, properties: any = {}, alias: string = "PROJECT.EnemyShooting") {
      super(transform, scene, properties, alias);
    }

    protected start(): void {
      // Setting up the references.
      this.player = TOOLKIT.SceneManager.FindGameObjectWithTag(this.scene, "Player") as BABYLON.TransformNode;
      this.bulletSpawnPoint = this.transform;
      this.playerHealth = this.player ? TOOLKIT.SceneManager.GetComponent(this.player, "PROJECT.PlayerHealth") as PROJECT.PlayerHealth : null;
      this.enemyHealth = TOOLKIT.SceneManager.GetComponent(this.transform, "PROJECT.EnemyHealth") as PROJECT.EnemyHealth;
      this.enemyMovement = TOOLKIT.SceneManager.GetComponent(this.transform, "PROJECT.EnemyMovement") as PROJECT.EnemyMovement;
    }

    protected update(): void {
      // Add the time since Update was last called to the timer.
      this.timer += this.getDeltaTime();

      // If the timer exceeds the time between attacks, the player is in range and this enemy is alive...
      if (
        this.timer >= this.timeBetweenShootings &&
        this.enemyMovement.isPlayerInRange &&
        this.enemyHealth.currentHealth > 0
      ) {
        // ... attack.
        this.attack();
      }
    }

    private attack(): void {
      // Reset the timer.
      this.timer = 0;

      // If the player has health to lose...
      if (this.playerHealth.currentHealth > 0) {
        // Get bullet container
        let bulletContainer = SM.GetAssetContainer(this.scene, "enemybullet.glb");
        
        // Use the enemy's CURRENT forward direction (where it's actually facing)
        let forward: BABYLON.Vector3 = new BABYLON.Vector3(0, 0, 1);
        if (this.transform.rotationQuaternion) {
          // Get forward direction from rotation quaternion
          let rotationMatrix = new BABYLON.Matrix();
          BABYLON.Matrix.FromQuaternionToRef(this.transform.rotationQuaternion, rotationMatrix);
          forward = BABYLON.Vector3.TransformNormal(forward, rotationMatrix);
        } else {
          // Fallback: use rotation euler angles
          forward = new BABYLON.Vector3(
            Math.sin(this.transform.rotation.y),
            0,
            Math.cos(this.transform.rotation.y)
          );
        }
        forward.normalize();
        
        const spawnPointPosition = this.bulletSpawnPoint.getAbsolutePosition();
        const spawnOffset = new BABYLON.Vector3(0, 1.3, 0); // Raise spawn point
        const forwardOffset = forward.scale(2); // 5 units forward to clear enemy collider
        const finalSpawnPosition = spawnPointPosition.add(spawnOffset).add(forwardOffset);
        
        // Instantiate bullet outside enemy collider
        let bulletClone: BABYLON.TransformNode = SM.InstantiatePrefabFromContainer(
          bulletContainer, 
          "EnemyBullet",
          "EnemyBullet_Clone",
          null,
          finalSpawnPosition,
          BABYLON.Quaternion.Identity()
        );
        
        if (!bulletClone) {
          SM.ConsoleError("EnemyShooting: Failed to instantiate 'EnemyBullet' prefab.");
          return;
        }
        
        // Apply force in the direction the enemy is facing
        if (bulletClone.physicsBody) {
          bulletClone.physicsBody.applyImpulse(forward.scale(this.BulletForce), bulletClone.position);
        }
      }
    }
  }
}
// Pseudocode generated by codewrx.ai