namespace PROJECT {
  export class EnemyShooting extends TOOLKIT.ScriptComponent {
    public timeBetweenShootings: number = 2;
    public damagePerShot: number = 10;
    public distanceToAttack: number = 15;
    public bullet: BABYLON.TransformNode;
    public BulletForce: number = 20;
    public bulletSpawnPoint: BABYLON.TransformNode;

    private player: BABYLON.TransformNode;
    private playerHealth: PROJECT.PlayerHealth;
    private enemyHealth: PROJECT.EnemyHealth;
    private enemyMovement: PROJECT.EnemyMovement;
    private timer: number = 0;

    constructor(transform: BABYLON.TransformNode, scene: BABYLON.Scene, properties: any = {}, alias: string = "PROJECT.EnemyShooting") {
      super(transform, scene, properties, alias);
    }

    protected start(): void {
      // Setting up the references.
      this.player = TOOLKIT.SceneManager.FindGameObjectWithTag(this.scene, "Player") as BABYLON.TransformNode;
      this.bulletSpawnPoint = this.transform;
      this.playerHealth = this.player ? TOOLKIT.SceneManager.GetComponent(this.player, "PROJECT.PlayerHealth") as PROJECT.PlayerHealth : null;
      this.enemyHealth = TOOLKIT.SceneManager.GetComponent(this.transform, "PROJECT.EnemyHealth") as PROJECT.EnemyHealth;
      this.enemyMovement = TOOLKIT.SceneManager.GetComponent(this.transform, "PROJECT.EnemyMovement") as PROJECT.EnemyMovement;
    }

    protected update(): void {
      // Add the time since Update was last called to the timer.
      this.timer += this.getDeltaTime();

      // If the timer exceeds the time between attacks, the player is in range and this enemy is alive...
      if (
        this.timer >= this.timeBetweenShootings &&
        this.enemyMovement.isPlayerInRange &&
        this.enemyHealth.currentHealth > 0
      ) {
        // ... attack.
        this.attack();
      }
    }

    private attack(): void {
      // Reset the timer.
      this.timer = 0;

      // If the player has health to lose...
      if (this.playerHealth.currentHealth > 0) {
        // Instantiate bullet
        // You must have a reference to the AssetContainer that contains the bullet prefab
        // For this example, we assume you have a property: bulletContainer: BABYLON.AssetContainer
        // If not, you must load or get it before instantiating
        if (!(this as any).bulletContainer) {
          // Try to get the asset container by name (replace 'BulletContainer' with your actual container name)
          (this as any).bulletContainer = TOOLKIT.SceneManager.GetAssetContainer(this.scene, "BulletContainer");
        }
        let bulletContainer = SM.GetAssetContainer(this.scene, "enemybullet.glb");
          const spawnPointPosition = this.bulletSpawnPoint.getAbsolutePosition();
          console.log("Spawn Point Position:", spawnPointPosition);
          const spawnOffset = new BABYLON.Vector3(0, 1.3, 0); // Raise by 1 unit (adjust as needed)
        // Add force to bullet
          let bulletClone: BABYLON.TransformNode = SM.InstantiatePrefabFromContainer(bulletContainer, "EnemyBullet","EnemyBullet_Clone",null,spawnPointPosition.add(spawnOffset),BABYLON.Quaternion.Identity());
          const forwardNudge = TOOLKIT.Utilities.GetForwardVector(this.transform).scale(2);
          bulletClone.position.addInPlace(forwardNudge);
          if (!bulletClone) {
            SM.ConsoleError("EnemyShooting: Failed to instantiate 'EnemyBullet' prefab.");
            return;
          }
          
          // Set initial position and rotation
        if (bulletClone.physicsBody) {
          let forward: BABYLON.Vector3 = this.transform.forward;
          bulletClone.physicsBody.applyImpulse(forward.scale(this.BulletForce), bulletClone.position);
        }
      }
    }
  }
}
// Pseudocode generated by codewrx.ai