namespace PROJECT {
  export class EnemyHealth extends TOOLKIT.ScriptComponent {
    public startingHealth: number = 100; // The amount of health the enemy starts the game with.
    public currentHealth: number; // The current health the enemy has.
    public scoreValue: number = 10; // The amount added to the player's score when the enemy dies.
    public deathClip: BABYLON.Sound; // The sound to play when the enemy dies.

    private deathAudio: TOOLKIT.AudioSource; // Reference to the audio source.
    private deathParticles: BABYLON.ParticleSystem; // Reference to the particle system that plays when the enemy is damaged.
    private boxCollider: BABYLON.Mesh; // Reference to the box collider.
    private isDead: boolean;

    constructor(transform: BABYLON.TransformNode, scene: BABYLON.Scene, properties: any = {}, alias: string = "PROJECT.EnemyHealth") {
      super(transform, scene, properties, alias);
    }

    protected start(): void {
      // Setting up the references.
      //this.deathAudio = TOOLKIT.SceneManager.GetComponent(this.transform, "TOOLKIT.AudioSource") as TOOLKIT.AudioSource;
      //this.deathParticles = TOOLKIT.SceneManager.GetComponent(this.transform, "BABYLON.ParticleSystem") as unknown as BABYLON.ParticleSystem;
      this.boxCollider = this.transform as BABYLON.Mesh;

      // Setting the current health when the enemy first spawns.
      this.currentHealth = this.startingHealth;
    }

    public takeDamage(amount: number, hitPoint: BABYLON.Vector3): void {
      // If the enemy is dead...
      if (this.isDead) {
        // ... no need to take damage so exit the function.
        return;
      }

      // Reduce the current health by the amount of damage sustained.
      this.currentHealth -= amount;

      // If the current health is less than or equal to zero...
      if (this.currentHealth <= 0) {
        // ... the enemy is dead.
        this.death();
      }
    }

    private async death(): Promise<void> {
      // The enemy is dead.
      this.isDead = true;

      // Turn the collider into a trigger so shots can pass through it.
      if (this.boxCollider && "isPickable" in this.boxCollider) {
        (this.boxCollider as BABYLON.Mesh).isPickable = false;
      }

      if (this.deathParticles) {
        this.deathParticles.start();
      }

      // Play the tank explosion sound effect.
      if (this.deathAudio) {
        this.deathAudio.play();
      }

      // Increase the score by the enemy's score value.
      (window as any).ScoreManager.score += this.scoreValue;

      // After 3 seconds destroy the enemy.
      await TOOLKIT.SceneManager.WaitForSeconds(3.0);
      if (this.transform) {
        TOOLKIT.SceneManager.SafeDestroy(this.transform);
      }
    }
  }
}
// Pseudocode generated by codewrx.ai