namespace PROJECT {
  export class PlayerBullet extends TOOLKIT.ScriptComponent {
    private playerShooting: PROJECT.PlayerShooting;
    private hitParticles: BABYLON.ParticleSystem;
    private hitAudio: TOOLKIT.AudioSource;
    private isDestroyed: boolean = false;

    constructor(transform: BABYLON.TransformNode, scene: BABYLON.Scene, properties: any = {}, alias: string = "PROJECT.PlayerBullet") {
      super(transform, scene, properties, alias);
    }

    protected awake(): void {
      this.enableCollisionEvents(); // Enable collision events
      let player = TOOLKIT.SceneManager.FindGameObjectWithTag(this.scene, "Player") as BABYLON.TransformNode;
      this.playerShooting = TOOLKIT.SceneManager.GetComponent(player, "PROJECT.PlayerShooting") as PROJECT.PlayerShooting;
      console.log("PlayerBullet awake: playerShooting =", this.playerShooting);
      // Debug collider setup
      if (!this.transform.physicsBody) {
        console.warn("PlayerBullet: No physicsBody on bullet!");
      } else {
        console.log("PlayerBullet: physicsBody exists", this.transform.physicsBody);
      }
      // Subscribing to the collision event
      this.onCollisionEnterObservable.add((otherTransform) => {
        this.handleCollision(otherTransform);
      });
    }

    private handleCollision(other: BABYLON.TransformNode): void {
      console.log("PlayerBullet collided with:", other.name);
      if (this.isDestroyed) return;
      // SAFETY CHECK: Ignore any collision with an object tagged "Player"
      if (TOOLKIT.SceneManager.GetTransformTag(other) === "Player") {
        return;
      }
      this.isDestroyed = true;
      // Check for Enemy tag
      if (TOOLKIT.SceneManager.GetTransformTag(other) === "Enemy") {
        const enemyHealth = TOOLKIT.SceneManager.GetComponent(other, "PROJECT.EnemyHealth") as PROJECT.EnemyHealth;
        if (enemyHealth && this.playerShooting) {
          enemyHealth.takeDamage(this.playerShooting.damagePerShot, other.position);
        }
      }
      // Destroy the bullet itself
      TOOLKIT.SceneManager.SafeDestroy(this.transform);
    }
  }
}
// Pseudocode generated by codewrx.ai