namespace PROJECT {
  export class PlayerBullet extends TOOLKIT.ScriptComponent {
    private playerShooting: PROJECT.PlayerShooting;
    private explosionParticles: PROJECT.BulletExplosionParticles;
    private hitAudio: TOOLKIT.AudioSource;
    private isDestroyed: boolean = false;

    constructor(transform: BABYLON.TransformNode, scene: BABYLON.Scene, properties: any = {}, alias: string = "PROJECT.PlayerBullet") {
      super(transform, scene, properties, alias);
    }

    protected start(): void {
      this.enableCollisionEvents();
      
      let player = TOOLKIT.SceneManager.FindGameObjectWithTag(this.scene, "Player") as BABYLON.TransformNode;
      this.playerShooting = TOOLKIT.SceneManager.GetComponent(player, "PROJECT.PlayerShooting") as PROJECT.PlayerShooting;
      
      // Get explosion particles component
      this.explosionParticles = TOOLKIT.SceneManager.GetComponent(this.transform, "PROJECT.BulletExplosionParticles") as PROJECT.BulletExplosionParticles;
      
      // Get audio source from child
      const children = this.transform.getChildren();
      if (children.length > 0) {
        const firstChild = children[0] as BABYLON.TransformNode;
        this.hitAudio = TOOLKIT.SceneManager.FindScriptComponent(firstChild, "TOOLKIT.AudioSource") as TOOLKIT.AudioSource;
      }
      
      // Subscribe to collision events
      this.onCollisionEnterObservable.add((otherTransform) => {
        this.handleCollision(otherTransform);
      });
    }

    private handleCollision(other: BABYLON.TransformNode): void {
      if (this.isDestroyed) return;
      
      // Note: Unity physics layers should prevent player bullet from hitting player
      // But we add a safety check anyway
      const otherTag = TOOLKIT.SceneManager.GetTransformTag(other);
      if (otherTag === "Player") {
        return;
      }
      
      this.isDestroyed = true;
      
      // Check for Enemy tag and apply damage
      if (otherTag === "Enemy") {
        const enemyHealth = TOOLKIT.SceneManager.GetComponent(other, "PROJECT.EnemyHealth") as PROJECT.EnemyHealth;
        if (enemyHealth && this.playerShooting) {
          enemyHealth.takeDamage(this.playerShooting.damagePerShot, other.position);
        }
      }
      
      // Play explosion particles at collision point
      if (this.explosionParticles) {
        this.explosionParticles.playExplosion(this.transform.position);
      }
      
      // Play audio
      if (this.hitAudio) {
        this.hitAudio.play();
      }
      
      // Destroy the bullet after short delay to let particles and audio play
      setTimeout(() => {
        if (this.transform && !this.transform.isDisposed()) {
          TOOLKIT.SceneManager.SafeDestroy(this.transform);
        }
      }, 800);
    }
  }
}
// Pseudocode generated by codewrx.ai