namespace PROJECT {
  export class PlayerMovement extends TOOLKIT.ScriptComponent {
    public speed: number = 22;
    public rotateSpeed: number = 180;
    private rotateVector: BABYLON.Vector3 = BABYLON.Vector3.Zero();

    private invertedControlFactor: number = 1;

    constructor(transform: BABYLON.TransformNode, scene: BABYLON.Scene, properties: any = {}, alias: string = "PROJECT.PlayerMovement") {
      super(transform, scene, properties, alias);
    }

    protected update(): void {
      const IC = TOOLKIT.InputController;
      const deltaTime: number = this.getDeltaTime();
      const horizontal: number = IC.GetUserInput(TOOLKIT.UserInputAxis.Horizontal);
      const vertical: number = IC.GetUserInput(TOOLKIT.UserInputAxis.Vertical);

      // Rotate around Y axis
      // this.transform.rotate(
      //   BABYLON.Axis.Y,
      //   horizontal * this.rotateSpeed * deltaTime * this.invertedControlFactor * (Math.PI / 180),
      //   BABYLON.Space.LOCAL
      // );

      const turnAngle = horizontal * this.rotateSpeed * 15 * deltaTime * this.invertedControlFactor * (Math.PI / 180);
      this.rotateVector.set(0, turnAngle, 0);
      this.transform.physicsBody.setAngularVelocity(this.rotateVector);

      // Move forward/backward
      const forward: BABYLON.Vector3 = this.transform.forward;
      const moveAmount: number = vertical * this.speed * 15 * deltaTime * this.invertedControlFactor;
      // this.transform.position.addInPlace(forward.scale(moveAmount));
      const moveVelocity = forward.scale(moveAmount);

      this.transform.physicsBody.setLinearVelocity(moveVelocity);

    }

    public invertControls(time: number): void {
      this.invertedControlsCourtine(time);
    }

    public async invertedControlsCourtine(time: number): Promise<void> {
      this.invertedControlFactor = -1;
      await TOOLKIT.SceneManager.WaitForSeconds(time);
      this.invertedControlFactor = 1;
    }

    public reduceSpeed(time: number): void {
      this.reduceSpeedCourtine(time);
    }

    public async reduceSpeedCourtine(time: number): Promise<void> {
      this.speed /= 3;
      this.rotateSpeed /= 3;
      await TOOLKIT.SceneManager.WaitForSeconds(time);
      this.speed *= 3;
      this.rotateSpeed *= 3;
    }
  }
}
// Pseudocode generated by codewrx.ai