namespace PROJECT {
  export class PlayerBullet extends TOOLKIT.ScriptComponent {
    private playerShooting: PROJECT.PlayerShooting;
    private hitParticles: BABYLON.ParticleSystem;
    private hitAudio: TOOLKIT.AudioSource;
    private isDestroyed: boolean = false;

    constructor(transform: BABYLON.TransformNode, scene: BABYLON.Scene, properties: any = {}, alias: string = "PROJECT.PlayerBullet") {
      super(transform, scene, properties, alias);
    }

    protected start(): void {
      this.enableCollisionEvents();
      
      let player = TOOLKIT.SceneManager.FindGameObjectWithTag(this.scene, "Player") as BABYLON.TransformNode;
      this.playerShooting = TOOLKIT.SceneManager.GetComponent(player, "PROJECT.PlayerShooting") as PROJECT.PlayerShooting;
      
      // Get child components for particle and audio
      const children = this.transform.getChildren();
      if (children.length > 0) {
        const firstChild = children[0] as BABYLON.TransformNode;
        
        // Find particle system
        for (let ps of this.scene.particleSystems) {
          if (ps.emitter === firstChild && ps instanceof BABYLON.ParticleSystem) {
            this.hitParticles = ps as BABYLON.ParticleSystem;
            break;
          }
        }
        
        // Find audio source
        this.hitAudio = TOOLKIT.SceneManager.FindScriptComponent(firstChild, "TOOLKIT.AudioSource") as TOOLKIT.AudioSource;
      }
      
      // Subscribe to collision events
      this.onCollisionEnterObservable.add((otherTransform) => {
        this.handleCollision(otherTransform);
      });
    }

    private handleCollision(other: BABYLON.TransformNode): void {
      if (this.isDestroyed) return;
      
      // Note: Unity physics layers should prevent player bullet from hitting player
      // But we add a safety check anyway
      const otherTag = TOOLKIT.SceneManager.GetTransformTag(other);
      if (otherTag === "Player") {
        return;
      }
      
      this.isDestroyed = true;
      
      // Check for Enemy tag and apply damage
      if (otherTag === "Enemy") {
        const enemyHealth = TOOLKIT.SceneManager.GetComponent(other, "PROJECT.EnemyHealth") as PROJECT.EnemyHealth;
        if (enemyHealth && this.playerShooting) {
          enemyHealth.takeDamage(this.playerShooting.damagePerShot, other.position);
        }
      }
      
      // Handle particle and audio effects
      if (this.hitParticles) {
        const particleEmitter = this.hitParticles.emitter as BABYLON.TransformNode;
        
        // Unparent the particles from the bullet
        if (particleEmitter) {
          particleEmitter.parent = null;
        }
        
        // Play particle system
        this.hitParticles.start();
        
        // Play audio
        if (this.hitAudio) {
          this.hitAudio.play();
        }
        
        // Schedule particle cleanup after duration
        if (particleEmitter) {
          const duration = this.hitParticles.targetStopDuration || 2.0;
          this.scheduleParticleCleanup(particleEmitter, duration);
        }
      }
      
      // Destroy the bullet
      TOOLKIT.SceneManager.SafeDestroy(this.transform);
    }
    
    private async scheduleParticleCleanup(emitter: BABYLON.TransformNode, duration: number): Promise<void> {
      await TOOLKIT.SceneManager.WaitForSeconds(duration);
      if (emitter && !emitter.isDisposed()) {
        TOOLKIT.SceneManager.SafeDestroy(emitter);
      }
    }
  }
}
// Pseudocode generated by codewrx.ai