namespace PROJECT {
  export class BulletExplosionParticles extends TOOLKIT.ScriptComponent {
    private explosionParticles: BABYLON.ParticleSystem;

    constructor(transform: BABYLON.TransformNode, scene: BABYLON.Scene, properties: any = {}, alias: string = "PROJECT.BulletExplosionParticles") {
      super(transform, scene, properties, alias);
    }

    protected start(): void {
      this.createExplosionParticles();
    }

    private createExplosionParticles(): void {
      // Create burst-style explosion matching Unity screenshot
      // Dense, visible burst of particles radiating outward
      this.explosionParticles = new BABYLON.ParticleSystem("BulletExplosion", 500, this.scene);
      
      // Duration: 2 (not looping)
      this.explosionParticles.targetStopDuration = 2;
      
      // Short lifetime for quick burst effect
      this.explosionParticles.minLifeTime = 0.3;
      this.explosionParticles.maxLifeTime = 0.6;
      
      // Medium outward speed for visible burst
      this.explosionParticles.minEmitPower = 3.0;
      this.explosionParticles.maxEmitPower = 6.0;
      
      // Medium-sized particles for visibility
      this.explosionParticles.minSize = 0.8;
      this.explosionParticles.maxSize = 1.5;
      
      // Random rotation
      this.explosionParticles.minInitialRotation = 0;
      this.explosionParticles.maxInitialRotation = 2 * Math.PI;
      
      // Bright yellow/orange explosion colors visible in screenshot
      this.explosionParticles.color1 = new BABYLON.Color4(1, 0.9, 0.6, 1);
      this.explosionParticles.color2 = new BABYLON.Color4(1, 0.8, 0.4, 1);
      this.explosionParticles.colorDead = new BABYLON.Color4(0.8, 0.6, 0.3, 0);
      
      // No gravity - pure outward burst
      this.explosionParticles.gravity = new BABYLON.Vector3(0, 0, 0);
      
      // Fast simulation
      this.explosionParticles.updateSpeed = 0.008;
      
      // No continuous emission - burst only
      this.explosionParticles.emitRate = 0;
      
      // Direction - radial burst in all directions
      this.explosionParticles.direction1 = new BABYLON.Vector3(-1, -0.5, -1);
      this.explosionParticles.direction2 = new BABYLON.Vector3(1, 1, 1);
      
      // Small sphere emitter for concentrated burst origin
      this.explosionParticles.createSphereEmitter(0.1, 1);
      
      // Use smoke/cloud texture
      this.explosionParticles.particleTexture = new BABYLON.Texture("https://assets.babylonjs.com/textures/cloud.png", this.scene);
      
      // Additive blending for bright, glowing explosion
      this.explosionParticles.blendMode = BABYLON.ParticleSystem.BLENDMODE_ADD;
      
      // Billboard rendering
      this.explosionParticles.billboardMode = BABYLON.ParticleSystem.BILLBOARDMODE_ALL;
      
      // Size: start medium, grow quickly, then shrink
      this.explosionParticles.addSizeGradient(0, 0.8);
      this.explosionParticles.addSizeGradient(0.2, 1.5);
      this.explosionParticles.addSizeGradient(0.6, 1.2);
      this.explosionParticles.addSizeGradient(1.0, 0.4);
      
      // Color: bright yellow/orange fading to dark
      this.explosionParticles.addColorGradient(0, new BABYLON.Color4(1, 1, 0.8, 1));
      this.explosionParticles.addColorGradient(0.2, new BABYLON.Color4(1, 0.8, 0.4, 0.9));
      this.explosionParticles.addColorGradient(0.5, new BABYLON.Color4(1, 0.6, 0.2, 0.6));
      this.explosionParticles.addColorGradient(1.0, new BABYLON.Color4(0.6, 0.4, 0.2, 0));
      
      // Rotation for dynamic look
      this.explosionParticles.minAngularSpeed = -2.0;
      this.explosionParticles.maxAngularSpeed = 2.0;
      
      // Don't auto-start - will be triggered on collision
    }

    public playExplosion(position: BABYLON.Vector3): void {
      if (this.explosionParticles) {
        // Set emitter to collision position
        this.explosionParticles.emitter = position.clone();
        
        // Emit large burst of particles for visible explosion (20-30 particles)
        this.explosionParticles.manualEmitCount = 25;
        this.explosionParticles.start();
        
        // Stop after particle lifetime (0.6 seconds max)
        setTimeout(() => {
          if (this.explosionParticles) {
            this.explosionParticles.stop();
          }
        }, 600);
      }
    }

    public dispose(): void {
      if (this.explosionParticles) {
        this.explosionParticles.dispose();
      }
    }
  }
}
// Pseudocode generated by codewrx.ai
