namespace PROJECT {
  export class AutoDestruction extends TOOLKIT.ScriptComponent {
    public timeToDie: number = 15.0; // How many seconds this object will survive

    constructor(transform: BABYLON.TransformNode, scene: BABYLON.Scene, properties: any = {}, alias: string = "PROJECT.AutoDestruction") {
      super(transform, scene, properties, alias);
    }

    protected async start(): Promise<void> {
      await TOOLKIT.SceneManager.WaitForSeconds(this.timeToDie);
      this.transform.dispose();
    }
  }
}
// Pseudocode generated by codewrx.ai