namespace PROJECT {
  export class RandomStartingPoint extends TOOLKIT.ScriptComponent {
    public spawnPointsName: string;
    private spawnPoints: BABYLON.TransformNode;

    constructor(transform: BABYLON.TransformNode, scene: BABYLON.Scene, properties: any = {}, alias: string = "PROJECT.RandomStartingPoint") {
      super(transform, scene, properties, alias);
    }

    protected start(): void {
      this.spawnPoints = TOOLKIT.SceneManager.FindGameObjectWithTag(this.scene, "SpawnPoints") as BABYLON.TransformNode;
      let spawnPointIndex: number = Math.floor(Math.random() * this.spawnPoints.getChildTransformNodes().length);
      let child: BABYLON.TransformNode = this.spawnPoints.getChildTransformNodes()[spawnPointIndex];
      this.transform.position.copyFrom(child.position);
    }
  }
}
// Pseudocode generated by codewrx.ai