namespace PROJECT {
  export class Event {
    public eventName: string;
    public eventObject: string | null;
    public spawnPercentage: number;

    constructor() {
      this.eventName = "";
      this.eventObject = null;
      this.spawnPercentage = 0;
    }
  }
}
// Pseudocode generated by codewrx.ai