namespace PROJECT {
  export class EventManager extends TOOLKIT.ScriptComponent {
    public gameEvents: PROJECT.Event[] = [];
    public bonusEvents: PROJECT.Event[] = [];
    public timeForNextEvent: number = 5;

    protected awake(): void {
        // Initialize game events with [name, prefab, percentage]
        const enemyData: [string, string, number][] = [
            ["Enemy", "enemy.glb", 5],       // Common enemy
            ["EnemyBoss", "enemyboss.glb", 2], // Medium rare
            ["Stone", "stone.glb", 3], // Rare
            ["Puddle", "puddle.glb", 3], // Very rare
            ["TNT", "tnt.glb", 1]   // Super rare
        ];
        
        for (const [name, prefix, percentage] of enemyData) {
            const gameEvent = new PROJECT.Event();
            gameEvent.eventName = name;
            gameEvent.eventObject = prefix;
            gameEvent.spawnPercentage = percentage;
            this.gameEvents.push(gameEvent);
        }

        // Initialize bonus events with [name, prefab, percentage]
        const bonusData: [string, string, number][] = [
            ["Heart", "heart.glb", 2],  // Most common bonus
            ["StrongerWeapon", "strongerWeapon.glb", 3],   // Medium bonus
            ["Shield", "shield.glb", 1]  // Rare bonus
        ];

        for (const [name, prefix, percentage] of bonusData) {
            const bonusEvent = new PROJECT.Event();
            bonusEvent.eventName = name;
            bonusEvent.eventObject = prefix;
            bonusEvent.spawnPercentage = percentage;
            this.bonusEvents.push(bonusEvent);
        }
    }
    public nextRound: number = 6;
    public percentageForBonus: number = 50;

    private playerHealth: PROJECT.PlayerHealth;

    constructor(transform: BABYLON.TransformNode, scene: BABYLON.Scene, properties: any = {}, alias: string = "PROJECT.EventManager") {
      super(transform, scene, properties, alias);
    }

    protected start(): void {
      const playerTransform = TOOLKIT.SceneManager.FindGameObjectWithTag(this.scene, "Player");
      console.log("Player Transform:", playerTransform);
      if (playerTransform) {
        this.playerHealth = TOOLKIT.SceneManager.GetComponent(playerTransform, "PROJECT.PlayerHealth") as PROJECT.PlayerHealth;
      }
      if (this.playerHealth) {
        this.gameLoopCoroutine();
      } else {
        TOOLKIT.SceneManager.ConsoleError("EventManager: PlayerHealth not found. Game loop will not start.");
      }
    }

    private async gameLoopCoroutine(): Promise<void> {
      let eventsCounter: number = 0;
      while (this.playerHealth && this.playerHealth.currentHealth > 0) {
        eventsCounter++;
        await TOOLKIT.SceneManager.WaitForSeconds(this.timeForNextEvent);
        let condition: boolean = Math.floor(Math.random() * 100) < this.percentageForBonus;
        let selectedEvent: PROJECT.Event = this.randomEventSelection(condition ? this.bonusEvents : this.gameEvents);
        if (selectedEvent != null && selectedEvent.eventObject != "") {
          let container = SM.GetAssetContainer(this.scene, selectedEvent.eventObject);

          let object: BABYLON.TransformNode = SM.InstantiatePrefabFromContainer(container, selectedEvent.eventName, selectedEvent.eventName + "Clone");

          // Raise enemy spawn position by 2 units above ground
          object.position.y += 2;
        }
        if (eventsCounter % this.nextRound === 0) {
          this.percentageForBonus -= 5;
          this.percentageForBonus = Math.max(this.percentageForBonus, 0);
        }
      }
    }

    private randomEventSelection(events: PROJECT.Event[]): PROJECT.Event {
      let total: number = 0;
      for (let e of events) {
        total += e.spawnPercentage;
      }

      let rand: number = Math.floor(Math.random() * total);
      let downLimit: number = 0;
      let selectedEvent: PROJECT.Event = null;

      for (let e of events) {
        if (rand >= downLimit && rand < downLimit + e.spawnPercentage) {
          selectedEvent = e;
          break;
        }
        downLimit += e.spawnPercentage;
      }

      return selectedEvent;
    }
  }
}
// Pseudocode generated by codewrx.ai