namespace PROJECT {
  export class GameOverManager extends TOOLKIT.ScriptComponent {
    public playerHealth: PROJECT.PlayerHealth; // Reference to the player's health.

    private anim: TOOLKIT.AnimationState; // Reference to the animator component.

    constructor(transform: BABYLON.TransformNode, scene: BABYLON.Scene, properties: any = {}, alias: string = "PROJECT.GameOverManager") {
      super(transform, scene, properties, alias);
    }

    protected awake(): void {
      // Set up the reference.
      this.anim = TOOLKIT.SceneManager.GetComponent(this.transform, "TOOLKIT.AnimationState") as TOOLKIT.AnimationState;
    }

    protected start(): void {
      // Auto-assign playerHealth if not set
      if (!this.playerHealth) {
        const playerTransform = TOOLKIT.SceneManager.FindGameObjectWithTag(this.scene, "Player");
        if (playerTransform) {
          this.playerHealth = TOOLKIT.SceneManager.GetComponent(playerTransform, "PROJECT.PlayerHealth") as PROJECT.PlayerHealth;
        }
      }
      if (this.playerHealth) {
        this.checkGameOver();
      } else {
        TOOLKIT.SceneManager.ConsoleError("GameOverManager: PlayerHealth not found. Game over check will not start.");
      }
    }

    private async checkGameOver(): Promise<void> {
      // While the player has health...
      while (this.playerHealth && this.playerHealth.currentHealth > 0) {
        await TOOLKIT.SceneManager.WaitForSeconds(0.3);
      }
      if (!this.playerHealth) {
        TOOLKIT.SceneManager.ConsoleError("GameOverManager: PlayerHealth is undefined at game over.");
        return;
      }
      // Tell the animator the game is over...
      this.anim.setTrigger("GameOver");
      await TOOLKIT.SceneManager.WaitForSeconds(3);
      window.location.reload();
    }
  }
}
// Pseudocode generated by codewrx.ai