namespace PROJECT {
  export class GameOverManager extends TOOLKIT.ScriptComponent {
    public playerHealth: PROJECT.PlayerHealth; // Reference to the player's health.

    private anim: TOOLKIT.AnimationState; // Reference to the animator component.
    
    // UI Elements
    private advancedTexture: BABYLON.GUI.AdvancedDynamicTexture;
    private gameOverText: BABYLON.GUI.TextBlock;

    constructor(transform: BABYLON.TransformNode, scene: BABYLON.Scene, properties: any = {}, alias: string = "PROJECT.GameOverManager") {
      super(transform, scene, properties, alias);
    }

    protected awake(): void {
      // Set up the reference.
      this.anim = TOOLKIT.SceneManager.GetComponent(this.transform, "TOOLKIT.AnimationState") as TOOLKIT.AnimationState;
      
      // Create UI
      this.createGameOverUI();
      
      console.log("GameOverManager: UI created successfully!");
    }

    private createGameOverUI(): void {
      // Create fullscreen UI
      this.advancedTexture = BABYLON.GUI.AdvancedDynamicTexture.CreateFullscreenUI("GameOverUI", true, this.scene);

      // Game Over Text - Centered
      this.gameOverText = new BABYLON.GUI.TextBlock("GameOverText");
      this.gameOverText.text = "GAME OVER";
      this.gameOverText.color = "red";
      this.gameOverText.fontSize = 96;
      this.gameOverText.fontWeight = "bold";
      this.gameOverText.textHorizontalAlignment = BABYLON.GUI.Control.HORIZONTAL_ALIGNMENT_CENTER;
      this.gameOverText.textVerticalAlignment = BABYLON.GUI.Control.VERTICAL_ALIGNMENT_CENTER;
      this.gameOverText.horizontalAlignment = BABYLON.GUI.Control.HORIZONTAL_ALIGNMENT_CENTER;
      this.gameOverText.verticalAlignment = BABYLON.GUI.Control.VERTICAL_ALIGNMENT_CENTER;
      this.gameOverText.alpha = 0; // Hidden by default
      this.advancedTexture.addControl(this.gameOverText);
    }

    protected start(): void {
      // Auto-assign playerHealth if not set
      if (!this.playerHealth) {
        const playerTransform = TOOLKIT.SceneManager.FindGameObjectWithTag(this.scene, "Player");
        if (playerTransform) {
          this.playerHealth = TOOLKIT.SceneManager.GetComponent(playerTransform, "PROJECT.PlayerHealth") as PROJECT.PlayerHealth;
        }
      }
      if (this.playerHealth) {
        this.checkGameOver();
      }
    }

    private async checkGameOver(): Promise<void> {
      // While the player has health...
      while (this.playerHealth && this.playerHealth.currentHealth > 0) {
        await TOOLKIT.SceneManager.WaitForSeconds(0.3);
      }
      if (!this.playerHealth) {
        return;
      }
      
      // Show game over text
      if (this.gameOverText) {
        this.gameOverText.alpha = 1;
      }
      
      // Tell the animator the game is over...
      if (this.anim) {
        this.anim.setTrigger("GameOver");
      }
      
      await TOOLKIT.SceneManager.WaitForSeconds(3);
      
      // Reload scene
      window.location.reload();
    }
  }
}
// Pseudocode generated by codewrx.ai