namespace PROJECT {
  export class ScoreManager extends TOOLKIT.ScriptComponent {
    public static score: number = 0; // The player's score.

  private text: BABYLON.GUI.TextBlock; // Reference to the Babylon.js GUI TextBlock.

    constructor(transform: BABYLON.TransformNode, scene: BABYLON.Scene, properties: any = {}, alias: string = "PROJECT.ScoreManager") {
      super(transform, scene, properties, alias);
    }

    protected awake(): void {
      // Set up the reference to a Babylon.js GUI TextBlock named "ScoreText" (adjust name as needed)
      let advancedTexture = BABYLON.GUI.AdvancedDynamicTexture.CreateForMesh(this.transform as BABYLON.Mesh);
      this.text = advancedTexture.getControlByName("ScoreText") as BABYLON.GUI.TextBlock;

      // Reset the score.
      PROJECT.ScoreManager.score = 0;
    }

    protected update(): void {
      // Set the displayed text to be the word "Score" followed by the score value.
      if (this.text) {
        this.text.text = "Score: " + PROJECT.ScoreManager.score;
      }
    }
  }
}
// Pseudocode generated by codewrx.ai