namespace PROJECT {
  export class ScoreManager extends TOOLKIT.ScriptComponent {
    public static score: number = 0; // The player's score.

    private scoreText: BABYLON.GUI.TextBlock; // GUI TextBlock for score display
    private advancedTexture: BABYLON.GUI.AdvancedDynamicTexture; // UI texture

    constructor(transform: BABYLON.TransformNode, scene: BABYLON.Scene, properties: any = {}, alias: string = "PROJECT.ScoreManager") {
      super(transform, scene, properties, alias);
    }

    protected awake(): void {
      // Create fullscreen UI
      this.advancedTexture = BABYLON.GUI.AdvancedDynamicTexture.CreateFullscreenUI("ScoreUI", true, this.scene);
      
      // Create Score Text - Top Left
      this.scoreText = new BABYLON.GUI.TextBlock("ScoreText");
      this.scoreText.text = "SCORE: 0";
      this.scoreText.color = "white";
      this.scoreText.fontSize = 32; // Reduced from 48 to 32
      this.scoreText.fontWeight = "bold";
      this.scoreText.textHorizontalAlignment = BABYLON.GUI.Control.HORIZONTAL_ALIGNMENT_LEFT;
      this.scoreText.textVerticalAlignment = BABYLON.GUI.Control.VERTICAL_ALIGNMENT_TOP;
      this.scoreText.horizontalAlignment = BABYLON.GUI.Control.HORIZONTAL_ALIGNMENT_LEFT;
      this.scoreText.verticalAlignment = BABYLON.GUI.Control.VERTICAL_ALIGNMENT_TOP;
      this.scoreText.left = 20;
      this.scoreText.top = 40; // Moved down from 20 to 40
      this.scoreText.width = "300px"; // Reduced from 400px to 300px
      this.scoreText.height = "50px"; // Reduced from 60px to 50px
      this.advancedTexture.addControl(this.scoreText);

      // Reset the score
      PROJECT.ScoreManager.score = 0;
      
      console.log("ScoreManager: UI created successfully!");
    }

    protected update(): void {
      // Update the score display
      if (this.scoreText) {
        this.scoreText.text = "SCORE: " + PROJECT.ScoreManager.score;
      }
    }
  }
}
// Pseudocode generated by codewrx.ai